#!/usr/bin/env python3
# Optional preview wrappers. If matplotlib is installed, each plotting section should call
# plt.show() for visual confirmation before saving. The production SVG figures were
# generated by analyze_mitogenomes.py without third-party dependencies.
import matplotlib.pyplot as plt
# ... plotting commands ...
plt.show()
plt.savefig('analysis_results/figures/preview_figure.png', dpi=300, bbox_inches='tight')
